### ISSUE TITLE
Set up pregenerated test cases

### ISSUE THREAD

**Issue by kj800x** [Emporophobe/WikiRacer#15]
Do we want to always be running on the same exact pages for each run of the program, or do we want to regenerate the test cases on every run (and keep them fixed between the different algorithms)?

- Select n test cases (maybe save them to a file so that we can replicate the results)
- Run each heuristic for each test case and keep track of the result.

**Comment by libreite** [comment]
I think we should run the exact same test cases every time. Does anyone else have strong opinions on this?

**Comment by kj800x** [comment]
I think that makes the most sense to me. I mostly included the comment because I wasn't sure which we meant when we discussed this earlier.

Perhaps we have one command which generates the test cases, validates that they are valid nodes, and then writes that to a file.
All the other commands could read from that file and use the test cases in that file.

**Comment by libreite** [comment]
Sure, sounds good
