### ISSUE TITLE
nltk resources not being downloaded properly

### ISSUE THREAD

**Issue by kj800x** [Emporophobe/WikiRacer#36]
Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

This should be included in the heuristics which need these resources

**Comment by libreite** [comment]
Which files need that? I'm only seeing files that use `nltk.download('stopwords')`

**Comment by kj800x** [comment]
I don't know. All I know is that I got these two errors when I ran the program. Maybe punkt is required by some function that someone calls
